"""add contact_email to banks and create agent_commands

Revision ID: 3902750cf60f
Revises: c9a1e4f6b3d7
Create Date: 2026-07-21 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3902750cf60f'
down_revision: Union[str, Sequence[str], None] = 'c9a1e4f6b3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written rather than autogenerated: alembic/env.py doesn't import
# loan_recommendation.models, so `banks`/`bank_loan_policies` have never
# been visible to autogenerate — they exist only via Base.metadata.create_all()
# in main.py. This assumes the `banks` table already exists (true on the
# deployed server; would fail against a brand-new empty database that has
# never had the app started against it once).


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    if 'banks' in table_names:
        bank_columns = {c['name'] for c in inspector.get_columns('banks')}
        bank_indexes = {i['name'] for i in inspector.get_indexes('banks')}

        if 'contact_email' not in bank_columns:
            op.add_column('banks', sa.Column('contact_email', sa.String(), nullable=True))
        if 'ix_banks_contact_email' not in bank_indexes:
            op.create_index('ix_banks_contact_email', 'banks', ['contact_email'], unique=True)

    # agent_commands may already exist: it's a new table whose model is
    # visible to main.py's Base.metadata.create_all(), so on a server that
    # started the app after this model was added, create_all() creates it
    # (with whatever columns the model has *at that time*, which can be
    # ahead of this migration's original shape) before this migration runs.
    if 'banks' in table_names and 'agent_commands' not in table_names:
        op.create_table(
            'agent_commands',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('scenario', sa.String(), nullable=False),
            sa.Column('query', sa.Text(), nullable=False),
            sa.Column('loan_type', sa.String(), nullable=True),
            sa.Column('bank_id', sa.Integer(), sa.ForeignKey('banks.id'), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
        )
        inspector = sa.inspect(bind)
        table_names = set(inspector.get_table_names())
    if 'agent_commands' in table_names:
        agent_command_indexes = {i['name'] for i in inspector.get_indexes('agent_commands')}
        if 'ix_agent_commands_id' not in agent_command_indexes:
            op.create_index('ix_agent_commands_id', 'agent_commands', ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    if 'agent_commands' in table_names:
        agent_command_indexes = {i['name'] for i in inspector.get_indexes('agent_commands')}
        if 'ix_agent_commands_id' in agent_command_indexes:
            op.drop_index('ix_agent_commands_id', table_name='agent_commands')
        op.drop_table('agent_commands')

    if 'banks' in table_names:
        bank_columns = {c['name'] for c in inspector.get_columns('banks')}
        bank_indexes = {i['name'] for i in inspector.get_indexes('banks')}
        if 'ix_banks_contact_email' in bank_indexes:
            op.drop_index('ix_banks_contact_email', table_name='banks')
        if 'contact_email' in bank_columns:
            op.drop_column('banks', 'contact_email')
