"""add required_documents to bank_loan_rates

Revision ID: de82eb8d06af
Revises: 1dc8f7efd6d5
Create Date: 2026-07-03 12:20:46.616658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de82eb8d06af'
down_revision: Union[str, Sequence[str], None] = '1dc8f7efd6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_loan_rates', sa.Column('required_documents', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_loan_rates', 'required_documents')
    # ### end Alembic commands ###
